import Head from 'next/head'
import {AiFillTwitterCircle, AiFillMail, AiFillLinkedin, AiFillGithub, AiOutlineLink} from 'react-icons/ai'
import {SiCplusplus, SiJavascript, SiTailwindcss, SiMongodb, SiNodedotjs, SiReact} from 'react-icons/si'
import Image from 'next/image'
import josh from '../josh.jpg'
import jd from '../jd.jpg'
import zeus from '../handofzeus.jpg'
import dora from '../dora.jpg'
import track from '../Traxxxker.jpg'
import tr from '../TR.png'
import tho from '../THO.jpg'
import casl from '../CASL.png'
import ucsb from '../ucsb.gif'
import jbc from '../jbc.png'
import Link from 'next/link'
import About from './about'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Josh Dewhurst Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-100 px-10">
    <section className='p-10'>
      {/* <nav className="py-10 mb-5 flex justify-end">
        
        <ul className="flex items-center">
          <li>
            <a href="/about" className="text-white bg-cyan-300 px-4 ml-8 py-2 rounded hover:bg-cyan-500">About Me</a>
          </li>
          <li>
            <a href="#" className="text-white bg-cyan-300 px-4 ml-8 py-2 rounded hover:bg-cyan-500">Projects</a>
          </li>
          <li>
            <a href="#" className="text-white bg-cyan-300 px-4 ml-8 py-2 rounded hover:bg-cyan-500">Contact Me</a>
          </li>
        </ul>
      </nav> */}
      <div className="text-center p-10">
        <h2 className="text-7xl py-2 text-gray-900 font-medium">Josh Dewhurst</h2>
        <div className="relative mx-auto rounded-full w-80 h-80 overflow-hidden mb-10 mt-10">
        <Image 
        src={josh}
        layout="fill"
        objectFit="cover"
        />
      </div>
        <h3 className="text-2xl py-2 text-gray-600">Software Engineer and Development Specialist</h3>
        <p className="text-medium py-5 leading-8 text-gray-800">
          Josh is full-stack software engineer with an emphasis in backend development and experience in project management and team development. Josh's core values both professionally and personally are: honest communication and collaboration, openness to growth and development, and an intentional commitment to uplifting marginalized communities that have been systematically subjugated.
        </p>
      </div>
    </section>
    <section>
      <div>
        <h3 className="text-3xl py-1">
          Recent Technical Projects
        </h3>
      </div>
      <div>
      <div className="text-center shadow-lg shadow-black bg-slate-200 p-10 rounded-xl my-10  dark:bg-white flex-1 hover:bg-slate-300">
                <div className='text-3xl hover:text-4xl'>
                <a href="https://github.com/joshdewhurst/hand-of-zeus">
                <AiFillGithub />
                </a>
                </div>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                The Hand of Zeus
              </h3>
              <p className="py-2">
              A C++ management system. Zues, the admin, is able to perform different oporations to change the system's data. C++ libraries will be used to track operations that create a new entry, delete an entry, or edit an entry within the database. The user will also be able to edit their username and password.
              </p>
              <div className='justify-center flex p-3'>
              <Image src={zeus} width={500} height={500} />
              </div>
              <p className="text-gray-800 py-1">C++
                <div className='justify-center text-2xl flex'>
                  <SiCplusplus />
                </div>
              </p>
            </div>
      </div>
      <div>
      <div className="text-center shadow-lg shadow-black bg-slate-200 p-10 rounded-xl my-10  dark:bg-white flex-1 hover:bg-slate-300">
              <div className='flex px-4'>
                <div className='text-3xl hover:text-4xl px-4'>
                  <a href="https://github.com/joshdewhurst/dora-client">
                  <AiFillGithub />
                  </a>
                  </div>
                  <div className='text-3xl hover:text-4xl px-4'>
                  <a href="https://doramusica.netlify.app/">
                  <AiOutlineLink />
                  </a>
                  </div>
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                d'ora
              </h3>
              <p className="py-6">
              d'ora is a react based Node.js application. The backend of our project dora Server uses Express.js along with a noSQL database called mongoDB. dora Client uses axios to connect with an API and gather information on songs and artist, which the user can interact with. Javascript is used throughout server and client sides. EJS (Embedded JavaScript Templating) and Tailwind are both used to design the interface that the user inteacts with. JWT(JSON Web Token) is used to protect a users data and authenticate them.
              </p>
              <div className='justify-center flex p-4'>
              <Image src={dora} width={500} height={500} />
              </div>

              <div className='justify-evenly flex p-4'>
                <p className="text-gray-800 py-1">JavaScript
                <div className='justify-center text-2xl flex'>
                <SiJavascript />
                </div>
                </p>
                <p className="text-gray-800 py-1">Express</p>
                <p className="text-gray-800 py-1">Tailwind
                <div className='justify-center text-2xl flex'>
                  <SiTailwindcss />
                </div>
                </p>
                <p className="text-gray-800 py-1">MongoDB and Mongoose
                <div className='justify-center text-2xl flex'>
                <SiMongodb />
                </div>
                </p>
                <p className="text-gray-800 py-1">Node.js
                <div className='justify-center text-2xl flex'>
                <SiNodedotjs />
                </div>
                </p>
                <p className="text-gray-800 py-1">Bcrypt</p>
                <p className="text-gray-800 py-1">React
                <div className='justify-center text-2xl flex'>
                <SiReact />
                </div>
                </p>
              </div>
            </div>
      </div>

      <div>
      <div className="text-center shadow-lg shadow-black bg-slate-200 p-10 rounded-xl my-10  dark:bg-white flex-1 hover:bg-slate-300">
              <div className='flex px-4'>
                <div className='text-3xl hover:text-4xl px-4'>
                  <a href="https://github.com/joshdewhurst/Traxxxker">
                  <AiFillGithub />
                  </a>
                  </div>
                  <div className='text-3xl hover:text-4xl px-4'>
                  <a href="https://traxxxker.fly.dev/">
                  <AiOutlineLink />
                  </a>
                  </div>
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Traxxxker
              </h3>
              <p className="py-6">
              Traxxxker is a full stack node application that allows a user to practice safer sex practices and educate themselves on sexual health topics. The user is able to log new sexual encounters and new sexual partners to keep track in the case of exposure to a sexually transmitted disease or other sexual health related news.
              </p>
              <div className='justify-center flex p-4'>
              <Image src={track} width={500} height={500} />
              </div>

              <div className='justify-evenly flex p-4'>
                <p className="text-gray-800 py-1">JavaScript
                <div className='justify-center text-2xl flex'>
                <SiJavascript />
                </div>
                </p>
                <p className="text-gray-800 py-1">Express</p>
                <p className="text-gray-800 py-1">Tailwind
                <div className='justify-center text-2xl flex'>
                  <SiTailwindcss />
                </div>
                </p>
                <p className="text-gray-800 py-1">MongoDB and Mongoose
                <div className='justify-center text-2xl flex'>
                <SiMongodb />
                </div>
                </p>
                <p className="text-gray-800 py-1">Node.js
                <div className='justify-center text-2xl flex'>
                <SiNodedotjs />
                </div>
                </p>
                <p className="text-gray-800 py-1">Bcrypt</p>
                <p className="text-gray-800 py-1">React
                <div className='justify-center text-2xl flex'>
                <SiReact />
                </div>
                </p>
              </div>
            </div>
      </div>

      <div className="text-center p-10 flex ">
                    <div className='flex flex-col p-10 w-100 basis-2/3'>
                        <h2 className="text-7xl py-2 text-gray-900 font-medium content-start col-span-2">About Me</h2>
                        <p className="p-4 text-1xl">
                            Hi! My name is Josh Dewhurst, and I am a software engineer with full-stack experience but an inclanation for back-end development. I am located in San Francisco, CA and I am interested in working within fintech, healthcare, and geosocial networking.
                        </p>
                        <p className="p-4 text-1xl">
                            In additional to software development, I also have experience with project and event management. I have overseen development on projects ranging from $5,000 to $800,000, and have built internal leadership initiatives to optamize team and company performance. 
                        </p>
                    </div>
                    <div className="relative mx-auto rounded-full h-80 overflow-hidden mb-10 mt-10 content-start w-80 col-span-1 p-10 ">
                    <Image 
                    src={jd}
                    layout="fill"
                    objectFit="cover"
                    />
                    </div>
                </div>

                <div>
                  <h3 className="text-3xl py-1">
                    Other Experience
                  </h3>
              </div>

              <div>
      <div className="text-center shadow-lg shadow-black bg-slate-200 p-10 rounded-xl my-10  dark:bg-white flex-1 hover:bg-slate-300">
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Project and Event Management
              </h3>
              <p className="py-2 text-start">
              Since 2015, I have successfully managed projects(technical and non-technical) and directed events on all scales. My projects have had budgets ranging from $5,000 to $800,000. I have managed teams of engineers in app development starting with concept creation to code excecution and post project reflections. My expertise is in leadership development and team optimization. I have created internal curriculum for annual reviews, onboarding, conflict resolution. I have lead stand-up for engineering teams of 25 engineers all working on seperate projects, and have experience with revenue review for maximizing company profits.  
              </p>

              <h4 className="text-lg font-medium pt-8 pb-2 object-left justify-start text-left">
                Companies and Organizations I have worked with:
              </h4>
              <div className='justify-center flex px-8-3 m-8'>
                <div className='justify-center text-2xl flex px-10'>
                <Image 
                    src={tr}
                    objectFit="cover"
                    width={80}
                    height={80}
              />
                </div>
              <div className='justify-center text-2xl flex px-10'>
              <Image 
                    src={tho}
                    objectFit="cover"
                    width={80}
                    height={80}
              />
              </div>
              <div className='justify-center text-2xl flex px-10'>
              <Image 
                    src={ucsb}
                    objectFit="cover"
                    width={80}
                    height={90}
              />
              </div>
              <div className='justify-center text-2xl flex px-10'>
              <Image 
                    src={casl}
                    objectFit="cover"
                    width={100}
                    height={80}
              />
              </div>
              </div>
            </div>
      </div>

              <div className='flex'>
                  <div className='basis-1/3 p-10'>
                  <Image 
                  src={jbc}
                  width={300}
                  height={300}
                  />
                  </div>
                  <h3 className="text-3xl py-1 basis 2/3 p-10 text-center">
                    Contact me
                    <div>
                      <p className='font-light text-base p-10'>
                        Please contact me further if you wish to connect professionally or personally. I am open to opportunities and connections within the tech field and beyond.
                      </p>
                      <div className='flex-col'>
                        <div className='flex p-4'>
                            <a href="mailto:joshuardewhurst@gmail.com.com" className='w-200 h-200 px-10'>
                              <AiFillMail 
                             width={200}
                             height={200}/>
                            </a>
                            <p className='text-xl font-normal'>
                          Send me an email.
                           </p>
                        </div>
                      <div className='flex p-4'>
                      <a href="https://github.com/joshdewhurst"  className='w-200 h-200 px-10'>
                        <AiFillGithub 
                        width={200}
                        height={200}/>
                       </a>
                       <p className='text-xl font-normal'>
                          Let's connect on LinkedIn.
                           </p>
                      </div>
                      <div className='flex p-4'>
                        <a href="https://www.linkedin.com/in/josh-dewhurst/"  className='w-200 h-200 px-10'>
                          <AiFillLinkedin 
                          width={200}
                          height={200}/>
                        </a>
                        <p className='text-xl font-normal'>
                          Check out my GitHub for all current projects and past repositories!
                        </p>
                      </div>

                      </div>

                    </div>
                  </h3>
              </div>

    </section>
      </main>
    </div>
  )
}
